-- ============================================================================
-- PROJECT: Waste2Menu — A Zero-Waste Reverse Recipe & Byproduct Optimization Engine
-- SEED DATASET (PostgreSQL / pgAdmin 4)
-- Contains 6 Categories, 35 Scraps (Complete Matrix), 35 Recipes, 4 Chennai Dispatches & Demo Users
-- ============================================================================

TRUNCATE TABLE ngo_dispatches, recipes, byproduct_scraps, scrap_categories, users RESTART IDENTITY CASCADE;

-- 1. INSERT DEMO USERS (Master Chef, Home Chef, NGO Rep)
INSERT INTO users (id, name, email, password_hash, role, affiliation) VALUES
(1, 'Chef Sanjeev Kapoor', 'chef@annapurna.org', 'chef123', 'master_chef', 'National Heritage Rasoi Guild'),
(2, 'Priya Sharma', 'home@annapurna.org', 'home123', 'home_chef', 'Rasoi Hero Community Cook'),
(3, 'Kavitha Raman', 'ngo@chennaifoodbank.org', 'ngo123', 'ngo_rep', 'Chennai Food Bank / No Food Waste');
SELECT setval('users_id_seq', (SELECT MAX(id) FROM users));

-- 2. INSERT 6 SCRAP CATEGORIES
INSERT INTO scrap_categories (id, name, short_name, icon_svg, description) VALUES
(1, '1. Vegetable Peels & Skins (Chilka / Khosha / Thol)', 'Vegetable Peels & Skins', '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-6h2v6zm0-8h-2V7h2v2z"/></svg>', 'Outer peels of gourds, tubers, roots, and nightshades rich in dietary fiber, polyphenols, and flavor.'),
(2, '2. Stems, Stalks & Green Leaves (Danta / Thandu / Leaves)', 'Stems, Stalks & Leaves', '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 2a10 10 0 0 0-7 17l5-5V9l2-2 2 2v5l5 5a10 10 0 0 0-7-17z"/></svg>', 'Nutrient-packed fibrous stalks, tender stems, and mineral-dense leaves of brassicas, herbs, and colocasia.'),
(3, '3. Seeds, Piths & Rinds (Beej / Bichi / Guthli)', 'Seeds, Piths & Rinds', '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><path d="M12 6v12M6 12h12"/></svg>', 'High-protein seeds, fibrous piths, melon rinds, and citrus peels packed with essential oils and pectin.'),
(4, '4. Grains, Starches & Leftover Staples (Basi / Leftover)', 'Grains & Staples', '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M2 12h20M12 2a15 15 0 0 1 0 20"/></svg>', 'Cooked rice, overnight stale rotis, bread crusts, starchy wash waters, and kanji rich in natural probiotics and energy.'),
(5, '5. Dairy & Spice Discards', 'Dairy & Spice Discards', '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M8 2h8l2 5H6l2-5zm0 5v13a2 2 0 0 0 2 2h4a2 2 0 0 0 2-2V7"/></svg>', 'Bio-active paneer whey, sour curd, caramelized ghee residue (khurchan), ginger skins, and roasted coconut husks.'),
(6, '6. Non-Veg Discards & Byproducts', 'Non-Veg Discards & Byproducts', '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M18 8c0-3.3-2.7-6-6-6S6 4.7 6 8c0 2.2 1.2 4.1 3 5.1V20a2 2 0 0 0 2 2h2a2 2 0 0 0 2-2v-6.9c1.8-1 3-2.9 3-5.1z"/><circle cx="9" cy="8" r="1"/><circle cx="15" cy="8" r="1"/></svg>', 'Nutrient-rich bone frames, marrow knuckles, fish heads, cartilage, prawn shells, chicken skin, and fish roe sacs.');
SELECT setval('scrap_categories_id_seq', (SELECT MAX(id) FROM scrap_categories));

-- 3. INSERT 35 BYPRODUCT SCRAPS (Complete 6-Category Matrix)
INSERT INTO byproduct_scraps (id, category_id, name_en, name_regional, common_uses) VALUES
(1, 1, 'Bottle Gourd Peels', 'Lauki Chilka, Lau-er Khosha, Sorakkay Thol', 'Stir-fried crisp with nigella seeds (Chechki / Bhaja), ground with roasted peanuts for chutney, or mixed into raita.'),
(2, 1, 'Ridge Gourd Peels', 'Turai Chilka, Jhinge Khosha, Peerkangai Thol', 'Coarsely roasted with urad dal, dried red chillies, and tamarind into Thogayal / Chutney / Bata.'),
(3, 1, 'Potato Peels', 'Aloo Chilka, Aloo Khosha, Urulaikizhangu Thol', 'Shallow-fried with poppy seeds (Posto Aloo Khosha Bhaja) or seasoned with chaat masala into crispy chips.'),
(4, 1, 'Raw Banana / Plantain Peels', 'Kacche Kele Ka Chilka, Kancha Kolar Khosha, Vazhakkai Thol', 'Boiled and mashed with mustard oil, garlic, and green chillies into Khosha Bata, or stir-fried into Kerala Thoran.'),
(5, 1, 'Pointed Gourd Peels', 'Parwal Chilka, Potol Khosha', 'Ground into a spicy paste with mustard paste, garlic, and green chillies (Potol Khosha Bata).'),
(6, 1, 'Pumpkin Peels & Fibers', 'Kaddu Chilka, Kumro Khosha, Parangikai Thol', 'Pan-roasted crisp with turmeric and cumin seeds, or slow-cooked into mixed-vegetable curries (Labra / Sambhar).'),
(7, 1, 'Bitter Gourd Peels', 'Karela Chilka, Korola Khosha, Pavakkai Thol', 'Salted to extract excess bitterness, mixed with besan (gram flour), and fried into crunchy, blood-sugar friendly fritters.'),
(8, 1, 'Carrot & Radish Skins', 'Gajar / Mooli Chilka, Mulo Khosha', 'Sautéed into quick dry subzis with mustard seeds or blended into mixed-peel chutneys.'),
(9, 1, 'Eggplant / Brinjal Peels', 'Baingan Chilka, Begun Khosha, Kathirikai Thol', 'Simmered in tangy yogurt/mustard gravies (e.g., Kashmiri Khatte Baingan peel curry).'),
(10, 2, 'Cauliflower Stems & Green Ribs', 'Phool Gobi Danthal, Fulkopi Danta, Cauliflower Thandu', 'Peeled and simmered into mustard paste gravies (Danta Chorchori), stir-fries with potatoes, or crunchy winter pickles.'),
(11, 2, 'Coriander & Mint Stems', 'Dhaniya Dandi, Dhonepata Danta, Kothamalli Thandu', 'Rich in volatile essential oils; blended into restaurant-style green chutney, soup bases, and marinades.'),
(12, 2, 'Broccoli Stalks', 'Broccoli Danthal', 'Woody exterior peeled away, core julienned into stir-fries, grated for paratha fillings, or pureed into soups.'),
(13, 2, 'Beetroot & Radish Greens', 'Chukandar / Mooli ke Patte, Mulo Saag', 'Finely chopped and cooked with garlic and green chillies into dry saag (Mooli Patte ki Sabzi).'),
(14, 2, 'Colocasia / Taro Stems & Leaves', 'Arbi ke Patte / Dandi, Kochur Saag, Chembu Ila', 'Steamed with spiced besan into pinwheel rolls (Patra / Patrode) or cooked with coconut-mustard paste.'),
(15, 2, 'Cabbage Outer Tough Leaves & Core', 'Patta Gobi ki Dandi & Patte', 'Shredded fine for quick stir-fried bhurji or slow-simmered in hearty vegetable broths.'),
(16, 3, 'Watermelon White Rind', 'Tarbooj ka Safed Chilka, Tarmooj Khosha', 'Diced and made into soft morning dosas (Kalingana Polo), sweet halwa/murabba, or savory spiced gravies.'),
(17, 3, 'Jackfruit Seeds', 'Kathal ke Beej, Enchorer Bichi, Palakottai', 'Dried, boiled, and cooked in thick lentil dals, roasted over open charcoal embers, or stewed in spicy gravies.'),
(18, 3, 'Pumpkin Seeds', 'Kaddu ke Beej, Kumror Bichi', 'Washed, sun-dried, and dry-roasted with black salt and cumin as a nutrient-dense zinc snack.'),
(19, 3, 'Raw Mango Pits & Skins', 'Aam ki Guthli, Aam Aantti, Maangai Kottai', 'Simmered inside summer rasams or dals for natural acidity, or dried into tangy dry aamchur pickles.'),
(20, 3, 'Squeezed Lemon / Lime Halves', 'Nichoda Hua Nimbu, Lebur Khosha', 'Stuffed with salt and turmeric, sun-cured in glass jars for 3 weeks into zero-waste probiotic lemon pickle.'),
(21, 4, 'Leftover Cooked Rice', 'Basi Bhaat, Pazhaya Saadham, Panta Bhaat', 'Soaked overnight in water with green chillies for fermented breakfast, or mashed into crispy rice pakoras.'),
(22, 4, 'Stale Rotis / Chapati Ends', 'Basi Roti, Pazhaya Roti', 'Torn into pieces and tempered with mustard seeds, onions, and curry leaves (Roti Poha / Seyal Phulka / Kutti Roti).'),
(23, 4, 'Stale Bread Crusts & Ends', 'Bread ke Kinare', 'Toasted dry and pulsed into homemade breadcrumbs, or prepared as spicy bread upma and shahi tukda bites.'),
(24, 4, 'Rice Wash Water', 'Chawal ka Paani, Dhowa Jal, Arisi Kalainja Thanneer', 'Used as a nutrient-rich cooking broth for dal, kneading soft roti dough, or as a mineral-rich soup base.'),
(25, 4, 'Cooked Rice Starch Water', 'Maanrh, Kanji Thanneer, Ganji', 'Seasoned with rock salt and roasted cumin as an energizing hydration tonic, or used as a gravy thickener.'),
(26, 5, 'Paneer / Chhena Whey Water', 'Paneer ka Paani, Chhanar Jal', 'High in complete protein; used to knead chapati dough, boil lentils, or form the liquid base of curries.'),
(27, 5, 'Sour Curd / Leftover Dahi', 'Khatta Dahi, Tok Doi, Puliya Thayir', 'Whisked with besan to make traditional Kadhi, rava dhokla fermenter, or South Indian Mor Kuzhambu.'),
(28, 5, 'Browned Ghee Sediment Residue', 'Mawa / Berukho / Khurchan / Mor Kali', 'Caramelized milk solids remaining in pan; tossed with hot rice and jaggery/sugar, or rolled into quick pedas.'),
(29, 5, 'Peeled Ginger Skins', 'Adrak ka Chilka, Ada-r Khosha, Inji Thol', 'Washed and dried, dropped directly into morning chai pots or boiled into immunity tisanes (kadha).'),
(30, 5, 'Coconut Brown Husk Skins', 'Nariyal ka Khurchan / Brown Skin', 'Shredded and dry-roasted with red chillies, tamarind, and garlic into flavorful dry idli podi.'),
(31, 6, 'Mutton & Chicken Bone Knuckles', 'Mutton Nalli, Chicken Haddi, Elumbu', 'Slow-simmered with peppercorns, crushed ginger, and turmeric into nutrient-dense bone broth (Nalli Soup / Yakhni).'),
(32, 6, 'Fish Head & Cartilage Trimmings', 'Machher Matha, Meen Thala', 'Fried with turmeric and slow-cooked into rich Bengali Muri Ghonto with fragrant rice, or simmered in spicy Assamese/South Indian sour gravies.'),
(33, 6, 'Prawn Shells & Heads', 'Chingri Khosha, Eral Odu', 'Roasted dry, crushed, and simmered with onions, garlic, and chillies to extract aromatic seafood broth or ground into spicy prawn shell chutney powder.'),
(34, 6, 'Chicken Skin & Fat Trimmings', 'Chicken Charbi', 'Rendered over low flame into natural cooking fat (schmaltz), and the crispy cracklings used as a crunchy garnish for pulav or dal.'),
(35, 6, 'Fish Roe / Egg Sacs', 'Machher Deem, Meen Muttai', 'Lightly seasoned with turmeric, salt, chopped green chillies, and onions, then pan-fried into crispy fish egg pakoras (Machher Deem-er Bora).');
SELECT setval('byproduct_scraps_id_seq', (SELECT MAX(id) FROM byproduct_scraps));

-- 4. INSERT 35 VERIFIED TRADITIONAL & MASTER CHEF RECIPES
INSERT INTO recipes (id, title, scrap_id, chef_name, chef_affiliation, prep_time_minutes, difficulty, course_type, dietary_type, pantry_staples, step_by_step_instructions, chef_wisdom_tip, servings) VALUES
(1, 'Lauki Chilka Chechki (Crispy Bottle Gourd Peel Stir-Fry)', 1, 'Maa Shanti Debi', 'Bengal Traditional Rasoi', 15, 'Easy', 'Crispy Bhaja/Side', 'Pure Veg', '["Mustard oil", "Kalonji (Nigella seeds)", "Green chillies", "Turmeric powder", "Salt"]'::jsonb, '["Wash the bottle gourd thoroughly before peeling. Slice the firm green peels into matchstick juliennes.", "Heat 1 tablespoon mustard oil in a cast-iron pan until smoking, then reduce flame and temper with 1/2 tsp kalonji and 2 slit green chillies.", "Add the julienned peels, turmeric, and salt. Saut\u00e9 on medium flame for 3 minutes.", "Cover with a lid and cook on low heat for 5-7 minutes until tender, then uncover and stir-fry on high flame for 2 minutes until crisp around edges.", "Serve hot with steamed rice and yellow masoor dal."]'::jsonb, 'Grandmother Wisdom: Always peel the lauki right before cooking. If peels are too thick, parboil for 90 seconds in salted water for extra tenderness.', 4),
(2, 'Peerkangai Thol Thogayal (Ridge Gourd Peel Chutney)', 2, 'Paati Meenakshi', 'Tamil Nadu Temple Kitchens', 18, 'Easy', 'Chutney/Dip', 'Vegan', '["Sesame (Gingelly) oil", "Urad dal", "Chana dal", "Dry red chillies", "Tamarind", "Asafoetida (Hing)", "Salt"]'::jsonb, '["Rinse ridge gourd peels in salted water. Chop roughly into 1-inch pieces.", "Heat 1 tablespoon sesame oil in a kadai. Roast 1 tbsp chana dal, 1 tbsp urad dal, 3 dry red chillies, and a pinch of hing until golden brown. Transfer to a plate.", "In the same pan, add the ridge gourd peels and saut\u00e9 on medium heat for 6-8 minutes until soft and raw smell disappears.", "Let the mixture cool completely. Add the roasted dals, a small marble-sized tamarind piece, salt, and 2 tablespoons of water.", "Coarsely grind in a mixie jar (do not make it watery paste). Serve with piping hot rice and a spoonful of ghee, or with crispy dosas."]'::jsonb, 'Paati Wisdom: The rough ridged strings carry natural roughage. A small splash of tamarind balances any underlying natural bitterness.', 4),
(3, 'Posto Aloo Khosha Bhaja (Potato Peel Poppy Seed Fry)', 3, 'Chef Sourav Ganguly', 'Kolkata Heritage Kitchen', 15, 'Easy', 'Crispy Bhaja/Side', 'Pure Veg', '["Mustard oil", "Whole poppy seeds (Posto)", "Dry red chilli", "Turmeric powder", "Kashmiri red chilli", "Salt"]'::jsonb, '["Scrub whole potatoes with a brush before peeling. Keep the peeled skins submerged in cold water to wash away residual starch.", "Dry the potato peels completely between clean kitchen towels.", "Heat 2 tablespoons mustard oil in a heavy-bottomed skillet until pungent and clear.", "Add one broken dry red chilli and immediately toss in the dried potato peels. Fry on high flame for 3 minutes with turmeric and salt.", "Reduce heat to medium and sprinkle 1.5 tablespoons of raw whole white poppy seeds (posto) over the crispy peels.", "Toss for 60 seconds until the poppy seeds turn fragrant and nutty. Serve immediately alongside rice and Biulir Dal."]'::jsonb, 'Chef Tip: Over 60% of a potato''s potassium and iron reside in the skin. Never discard skins of organically grown potatoes!', 4),
(4, 'Kancha Kolar Khosha Bata (Raw Banana Peel Pungent Mash)', 4, 'Didima Kalyani', 'Rural Bengal Home Kitchen', 20, 'Easy', 'Chutney/Dip', 'Pure Veg', '["Mustard oil", "Garlic cloves", "Green chillies", "Kalonji (Nigella)", "Salt", "Sugar (pinch)"]'::jsonb, '["Wash raw plantains. Slice off the green skin moderately thick and discard only the extreme stem ends.", "Boil the peels in water with 1/2 tsp turmeric and salt for 8-10 minutes until fork-tender. Drain water.", "In a small pan, heat 1 tsp mustard oil. Saut\u00e9 4 garlic cloves and 2 green chillies for 1 minute.", "Transfer boiled peels, sauteed garlic, chillies, and salt to a traditional sil-batta or small mixer grinder. Blend into a smooth, thick paste.", "Heat 1 tablespoon raw mustard oil in the pan, add 1/4 tsp kalonji, and pour the paste. Cook on low heat for 3-4 minutes until it leaves the sides of the pan.", "Finish with a drizzle of raw mustard oil. Best relished with first mouthful of piping hot rice."]'::jsonb, 'Didima Tip: Raw banana peels contain valuable resistant starch that acts as a natural prebiotic for gut health.', 4),
(5, 'Potol Khosha Bata (Pointed Gourd Peel Garlic Relish)', 5, 'Chef Tapas Bhowmik', 'East Bengal Heritage', 15, 'Easy', 'Chutney/Dip', 'Pure Veg', '["Parwal peels", "Garlic cloves", "Green chillies", "Kalonji", "Mustard oil", "Salt", "Sugar"]'::jsonb, '["Scrape pointed gourds lightly to remove sandy grit, wash, and peel outer skins.", "Coarsely grind the peels with 4 garlic cloves and 2 green chillies.", "Heat 1.5 tbsp mustard oil in a small iron skillet. Add kalonji and saute the ground paste.", "Cook stirring continuously on medium flame until moisture evaporates and paste turns deep olive green.", "Season with salt and a pinch of sugar to balance pungency."]'::jsonb, 'Chef Tip: Iron skillet caramelization gives this relish a distinct smoky depth.', 4),
(6, 'Kumro Khosha Bhaja (Crisp Pumpkin Peel Cumin Roast)', 6, 'Maa Gayatri', 'Odisha Village Kitchen', 14, 'Easy', 'Crispy Bhaja/Side', 'Pure Veg', '["Mustard oil", "Cumin seeds", "Turmeric", "Green chillies", "Salt"]'::jsonb, '["Slice the hard green pumpkin peel into thin long strips.", "Heat mustard oil, splutter cumin seeds and slit green chillies.", "Add pumpkin peel strips with turmeric and salt.", "Saut\u00e9 on high heat for 3 minutes, then medium for 6 minutes until charred and crispy.", "Serve hot with dal and rice."]'::jsonb, 'Wisdom: Pumpkin skins are dense in lutein and beta-carotene for eyesight protection.', 4),
(7, 'Karela Chilka Besan Fritters (Crunchy Bitter Gourd Crisps)', 7, 'Chef Pradeep Sharma', 'Rajasthan Marwari Rasoi', 16, 'Medium', 'Crispy Bhaja/Side', 'Pure Veg', '["Besan (Gram flour)", "Amchur powder", "Ajwain (Carom seeds)", "Red chilli powder", "Mustard oil", "Salt"]'::jsonb, '["Scrape rough ridged peels of bitter gourd. Massage with 1 tsp salt and rest for 15 minutes.", "Squeeze firmly between palms to extract bitter green juice.", "Dust peels with 2 tbsp besan, ajwain, amchur powder, and red chilli powder (no water needed; moisture from peel binds it).", "Pan-fry in hot mustard oil on low flame until crisp and golden brown.", "Sprinkle chaat masala and enjoy as crunchy side."]'::jsonb, 'Grandmother Wisdom: Squeezed karela peel juice can be added to drinking water for diabetic wellness.', 4),
(8, 'Gajar Mooli Chilka Rai Ki Subzi (Crunchy Mustard Tossed Peel Sauté)', 8, 'Nani Sushila Devi', 'Mathura Braj Rasoi', 12, 'Easy', 'Crispy Bhaja/Side', 'Pure Veg', '["Mustard seeds (Rai)", "Green chillies", "Turmeric powder", "Amchur (Dry mango powder)", "Mustard oil", "Salt"]'::jsonb, '["Wash carrots and radishes with a vegetable brush before peeling into long strips.", "Heat mustard oil in a pan, crackle black mustard seeds and slit green chillies.", "Add the peels, turmeric, and salt. Saut\u00e9 on medium flame for 5 minutes without covering so they stay crunchy.", "Finish with a pinch of amchur powder and serve as a tangy side accompaniment with dal and phulkas."]'::jsonb, 'Carrot skins hold high beta-carotene while radish skins possess natural pungency that softens beautifully when flash-sautéed.', 4),
(9, 'Begun Khosha Khatte Baingan Curry (Tangy Kashmiri Peel Gravy)', 9, 'Chef Rafiq Mir', 'Kashmiri Heritage Table', 20, 'Medium', 'Dry Sabzi', 'Pure Veg', '["Mustard oil", "Fennel seed powder (Saunf)", "Dry ginger powder (Sonth)", "Whisked curd", "Hing (Asafoetida)", "Salt"]'::jsonb, '["Collect glossy purple brinjal skins from roasted bharta preparations.", "Heat mustard oil, add hing, and saut\u00e9 the eggplant peels until softened and lightly browned.", "Stir in saunf and sonth powders mixed with 3 tablespoons of whisked sour curd and 1/4 cup warm water.", "Simmer on low flame for 8 minutes until the gravy coats the peels with deep purple color and tangy aroma."]'::jsonb, 'The deep violet color of brinjal skins is pure anthocyanin antioxidant; never throw it away when roasting bhartas!', 4),
(10, 'Fulkopi Danta Chorchori (Cauliflower Stem Mustard Medley)', 10, 'Chef Anirban Roy', 'Ma Mati Manush Community Collective', 25, 'Medium', 'Main Curry', 'Pure Veg', '["Mustard oil", "Yellow mustard paste", "Paanch Phoron", "Green chillies", "Turmeric", "Diced potato & brinjal (optional)", "Salt"]'::jsonb, '["Take the thick central stem and green ribs of cauliflower. Peel away the fibrous outer rind with a knife to reveal the tender translucent core.", "Slice the tender stalks into 2-inch matchsticks.", "Heat 1.5 tbsp mustard oil in a kadai. Splutter 1/2 tsp paanch phoron and 2 green chillies.", "Add the sliced cauliflower stems (and optional potato/brinjal pieces). Saut\u00e9 with turmeric and salt for 5 minutes.", "Add 1/2 cup warm water, cover and simmer on low heat for 12 minutes until stems are fork-tender.", "Uncover and stir in 2 tbsp fresh yellow mustard paste mixed with 2 tbsp water. Simmer for 2 minutes (do not boil hard or mustard turns bitter).", "Drizzle 1 tsp virgin mustard oil on top and serve with steamed rice."]'::jsonb, 'Chef Tip: The tender inner core of cauliflower stems is sweeter and crunchier than the florets themselves!', 4),
(11, 'Dhaniya Dandi Hari Chutney (Restaurant-Style Coriander Stem Dip)', 11, 'Chef Harpal Singh', 'Dhabas of Grand Trunk Road', 10, 'Easy', 'Chutney/Dip', 'Pure Veg', '["Coriander stems", "Green chillies", "Ginger", "Roasted cumin powder", "Black salt", "Lemon juice", "Chilled water / ice cube"]'::jsonb, '["Do not throw away the thick roots/stems of fresh coriander. Trim the brown base roots, wash stems thoroughly 3 times in cold water.", "Roughly chop the juicy green stems. They carry 80% of the volatile flavor oils of coriander.", "Add the stems to a blender with 2 green chillies, 1-inch ginger, 1/2 tsp roasted jeera powder, 1/2 tsp black salt, and 1 ice cube.", "Pulse into a bright emerald green paste. The ice cube prevents mixer heat from turning the chutney dark.", "Stir in fresh lemon juice. Perfect with samosas, pakoras, or smeared inside parathas."]'::jsonb, 'Master Tip: While leaves turn limp and oxidized, stems retain crisp acidity and vibrant chlorophyll oils for days.', 6),
(12, 'Broccoli Danthal Masala Paratha (Spiced Stem Stuffed Flatbread)', 12, 'Chef Simran Kaur', 'Punjab Farmhouse Rasoi', 25, 'Medium', 'Breakfast/Snack', 'Pure Veg', '["Whole wheat flour (Atta)", "Ajwain (Carom seeds)", "Green chillies", "Garam masala", "Ghee", "Salt"]'::jsonb, '["Peel the tough fibrous outer skin of broccoli stalks to expose the tender, jade-green sweet core.", "Grate the core finely using a box grater. Squeeze out excess moisture.", "Mix grated core with ajwain, chopped green chillies, garam masala, and salt to create the filling.", "Stuff into whole wheat dough pedas, roll gently, and roast on a hot tawa with ghee until speckled golden."]'::jsonb, 'Broccoli stalks are actually sweeter and crunchier than the florets once the exterior 1mm bark is peeled away.', 4),
(13, 'Mooli Ke Patte Ki Sabzi (Tender Radish Greens & Stalk Saag)', 13, 'Chef Baldev Ram', 'Punjab Pind Kitchens', 15, 'Easy', 'Main Curry', 'Pure Veg', '["Mustard oil", "Ajwain (Carom seeds)", "Garlic", "Hing", "Turmeric", "Salt"]'::jsonb, '["Separate fresh green radish leaves from roots. Wash in cold salted water to remove mud.", "Chop leaves and tender green stalks finely.", "Heat mustard oil in a kadai. Add ajwain and hing, followed by minced garlic.", "Toss in radish greens with turmeric and salt. Saut\u00e9 on medium flame without covering so greens retain vivid color.", "Cook 8 minutes until moisture evaporates. Serve with makki or bajra roti."]'::jsonb, 'Nani Tip: Radish leaves carry six times more Vitamin C and ten times more calcium than the radish root itself!', 4),
(14, 'Arbi Ke Patte Ki Patra (Colocasia Leaves Spiced Pinwheels)', 14, 'Chef Manjula Parikh', 'Saurashtra Traditional Kitchen', 30, 'Medium', 'Snack/Tiffin', 'Pure Veg', '["Colocasia leaves", "Besan", "Tamarind pulp", "Jaggery", "Garam masala", "Sesame seeds", "Mustard seeds"]'::jsonb, '["Wash colocasia leaves and roll over the back stems with a rolling pin to flatten fibrous veins.", "Make a thick paste of besan, tamarind pulp, jaggery, chilli powder, and salt.", "Smear paste evenly on back of each leaf, layer 3 leaves on top of each other, and roll tightly into a swiss roll cylinder.", "Steam in a steamer for 18 minutes until set and firm. Cool completely and slice into 1/2-inch round pinwheels.", "Shallow fry pinwheels in sesame and mustard seeds until exterior is crisp and nutty."]'::jsonb, 'Important Wisdom: Always use tamarind or sour mango with colocasia to neutralize calcium oxalate micro-crystals.', 6),
(15, 'Patta Gobi Dandi Bhurji (Crispy Shredded Cabbage Core Sauté)', 15, 'Dadi Parvati', 'Maharashtra Rural Kitchen', 15, 'Easy', 'Crispy Bhaja/Side', 'Vegan', '["Peanut oil", "Cumin seeds", "Curry leaves", "Roasted peanut powder", "Kashmiri red chilli", "Salt"]'::jsonb, '["Thinly slice the tough outer cabbage leaves and chop the dense white core into matchsticks.", "Heat peanut oil in a kadai, add cumin seeds, curry leaves, and green chillies.", "Toss in the cabbage core matchsticks and fry uncovered on high flame for 5 minutes for charred sweetness.", "Sprinkle coarsely crushed roasted peanuts and red chilli powder. Toss for 1 minute and serve hot."]'::jsonb, 'The central core contains high glutamic acid providing natural umami when sautéed at high heat.', 4),
(16, 'Kalingana Polo (Watermelon White Rind Soft Dosa)', 16, 'Amma Shardamba', 'Konkani Coastal Heritage', 20, 'Medium', 'Snack/Tiffin', 'Vegan', '["Dosa rice", "Grated watermelon white rind", "Fresh grated coconut", "Poha (flattened rice)", "Jaggery (optional)", "Salt"]'::jsonb, '["After enjoying the red sweet watermelon fruit, peel off and discard only the paper-thin hard green outer skin.", "Grate the firm, juicy white inner rind (approx. 2 cups).", "Soak 1 cup raw dosa rice for 4 hours. Drain and grind with grated watermelon rind, 3 tbsp fresh coconut, and 2 tbsp soaked poha.", "Do not add extra water \u2014 the watermelon rind releases ample natural moisture.", "The batter should be of medium pouring consistency. Add salt (and optional 1/2 tsp crushed jaggery). No overnight fermentation is required.", "Pour a ladleful onto a hot greased cast iron tawa without spreading too thin (like a set dosa). Cover with lid and cook on medium flame until soft and spongy.", "Serve hot with coconut chutney and spicy tomato gojju."]'::jsonb, 'Amma Wisdom: Watermelon white rind is rich in L-citrulline, an amino acid known to improve arterial circulation and muscle recovery.', 5),
(17, 'Kathal Beej Masala Dal (Jackfruit Seed Lentil Curry)', 17, 'Chef Jayanthi Ramesh', 'Kerala Malabar Coastal Kitchen', 25, 'Medium', 'Main Curry', 'Vegan', '["Jackfruit seeds", "Toor dal", "Coconut oil", "Mustard seeds", "Sambar powder", "Curry leaves", "Salt"]'::jsonb, '["Peel the hard white shell from jackfruit seeds. Leave thin brown skin intact.", "Cut seeds lengthwise in half. Pressure cook with toor dal and turmeric for 3 whistles.", "In a pot, temper coconut oil with mustard seeds, curry leaves, and dried red chillies.", "Add sambar powder, cooked dal-seed mixture, and salt. Simmer for 6 minutes.", "The seeds turn creamy like chestnuts and absorb all aromatic spices."]'::jsonb, 'Chef Tip: Jackfruit seeds have a rich chestnut-like starch and are zero-calorie compared to commercial nuts.', 5),
(18, 'Kaddu Beej Kala Namak Roast (Crunchy Spiced Zinc Snack)', 18, 'Vaidya Ramanathan', 'Kerala Ayurvedic Rasoi', 10, 'Easy', 'Breakfast/Snack', 'Vegan', '["Black salt (Kala namak)", "Roasted cumin powder", "Chaat masala", "Cold-pressed coconut oil", "Salt"]'::jsonb, '["Wash fresh pumpkin seeds in a colander to separate sticky orange stringy fibers.", "Dry thoroughly on a clean cotton towel in the sun or under a fan for 2 hours.", "Heat a heavy iron skillet, add 1/2 tsp coconut oil and dry-roast seeds on medium-low flame for 6-8 minutes until they puff and pop.", "Toss with black salt, cumin powder, and chaat masala. Cool and store in an airtight jar for crunchy snacking."]'::jsonb, 'Pumpkin seeds are nature''s richest whole-food source of zinc and magnesium; dry roasting activates digestive enzymes.', 6),
(19, 'Aam Guthli Rasam (Tangy Ancestral Raw Mango Pit Broth)', 19, 'Paati Alamelu', 'Thanjavur Kitchen Tradition', 25, 'Easy', 'Digestive Soup/Rasam', 'Vegan', '["Mustard seeds", "Crushed black pepper", "Cumin seeds", "Curry leaves", "Asafoetida (Hing)", "Sesame oil", "Salt"]'::jsonb, '["Save raw mango pits (guthli/aantti) with remaining pulp clinging to fibers from pickle making.", "Boil the pits in 3 cups of water with turmeric, salt, and slit green chillies for 15 minutes to release deep tangy essence.", "Discard the fibrous seed core, retaining the sour golden broth.", "Temper with sesame oil, mustard seeds, crushed cumin, black peppercorns, curry leaves, and a pinch of hing. Pour over hot rice."]'::jsonb, 'Mango stones contain natural tannins that clarify broth and calm summer Pitta dosha in Ayurveda.', 4),
(20, 'Sun-Cured Nimbu Chilka Probiotic Achar (Whole Squeezed Lemon Pickle)', 20, 'Dadi Nirmala', 'Braj Rasoi Heritage', 10, 'Easy', 'Chutney/Dip', 'Pure Veg', '["Squeezed lemon halves", "Rock salt / Sea salt", "Turmeric powder", "Kashmiri red chilli powder", "Ajwain", "Roasted fenugreek powder"]'::jsonb, '["Never discard lemon halves after squeezing juice for salads or lemonade.", "Cut squeezed lemon cups into quarters. Place in a sterile glass mason jar.", "Add 3 tablespoons rock salt and 1 teaspoon turmeric powder. Shake the jar vigorously.", "Place the jar in direct terrace sunshine for 14-21 days, shaking once daily.", "The tough rind softens completely into tender, translucent, probiotic-rich digestive pickle with zero added oil."]'::jsonb, 'Dadi Wisdom: Zero-oil sun curing preserves the precious limonene bioflavonoids in the yellow zest while cultivating beneficial wild lactic bacteria.', 10),
(21, 'Panta Bhaat / Pazhaya Saadham (Fermented Probiotic Rice Bowl)', 21, 'Gramin Rasoi Collective', 'Traditional Coastal India', 5, 'Easy', 'Snack/Tiffin', 'Vegan', '["Leftover cooked rice", "Drinking water", "Mustard oil", "Raw shallots / red onion", "Green chillies", "Rock salt"]'::jsonb, '["Take leftover cooked parboiled or white rice in a clean clay pot or ceramic bowl.", "Pour enough boiled and cooled drinking water to fully submerge the rice by 1 inch.", "Cover loosely with a clean muslin cloth or lid and let it ferment overnight (8-12 hours) at ambient room temperature (do not refrigerate).", "In the morning, the water turns cloudy and slightly effervescent with natural lactic acid bacteria.", "Season with rock salt, 1 teaspoon virgin raw mustard oil, and crush 1 green chilli and 3 pearl onions directly into the bowl with your fingers.", "Consume chilled on empty stomach for supreme summer body cooling and gut vitality."]'::jsonb, 'Scientific Fact: Overnight fermentation of rice multiplies its bioavailable iron content by up to 300% and generates natural vitamin B12.', 2),
(22, 'Basi Roti Seyal Phulka (Tempered Leftover Chapati Poha)', 22, 'Nani Hansa Ben', 'Gujarati & Sindhi Heritage Kitchen', 12, 'Easy', 'Snack/Tiffin', 'Pure Veg', '["Mustard seeds", "Cumin seeds", "Curry leaves", "Hing", "Turmeric", "Diced onions", "Tomatoes", "Roasted peanuts", "Lemon juice"]'::jsonb, '["Take 4-5 leftover chapatis from last night. Tear them into bite-sized 1-inch squares or pulse briefly in a mixie for coarse crumbs.", "Sprinkle 2 tablespoons of water or buttermilk over the pieces so they soften gently.", "Heat 1 tablespoon peanut oil in a kadai. Add mustard seeds, cumin seeds, hing, and fresh curry leaves.", "Add 2 tbsp raw peanuts and fry until crunchy. Toss in chopped onions and green chillies; saut\u00e9 until translucent.", "Add chopped tomatoes, turmeric, and salt. Cook until tomatoes turn mushy.", "Add the moistened roti pieces, toss vigorously on medium flame for 3 minutes until coated with spices.", "Finish with fresh chopped coriander and a generous squeeze of fresh lemon juice. Serve hot as comforting breakfast."]'::jsonb, 'Nani Wisdom: Stale wheat chapatis undergo starch retrogradation overnight, creating gut-friendly resistant starch with a lower glycemic index.', 3),
(23, 'Bread Kinare Masala Upma (Spicy Tempered Bread End Toss)', 23, 'Chef Meera Nair', 'Cochin Community Kitchen', 15, 'Easy', 'Breakfast/Snack', 'Vegan', '["Mustard seeds", "Urad dal", "Onions", "Tomatoes", "Curry leaves", "Turmeric", "Oil", "Salt"]'::jsonb, '["Cut stale bread heels and leftover crusts into bite-sized cubes.", "Heat oil in a wok. Splutter mustard seeds, urad dal, curry leaves, and sliced onions until golden brown.", "Add chopped tomatoes, turmeric, and salt. Cook until soft and saucy.", "Splash 2 tablespoons of water, toss in the dry bread cubes, and mix gently on high flame for 2 minutes until spiced and chewy."]'::jsonb, 'Stale bread absorbs spice temperings much better than fresh bread without turning into mush.', 4),
(24, 'Chawal Paani Aromatic Dal Tadka (Starchy Rice Water Simmered Dal)', 24, 'Dadi Kunti', 'Varanasi Ghat Kitchens', 25, 'Easy', 'Dal/Sambar', 'Pure Veg', '["Toor dal (Pigeon peas)", "Ghee", "Cumin seeds", "Garlic cloves", "Dry red chillies", "Salt"]'::jsonb, '["Collect the cloudy second rinse water from washing rice (Arisi Kalainja Thanneer / Dhowa Jal).", "Use this starch-rich, B-vitamin packed water instead of plain tap water to pressure-cook toor dal with turmeric and salt for 4 whistles.", "Whisk the cooked dal; notice the naturally thick, velvety texture imparted by the rice starches.", "Temper in hot ghee with cumin seeds, whole garlic, and dry red chillies. Pour over dal with sizzling aroma."]'::jsonb, 'Ancient Ayurvedic texts call rice wash water ''Tandulodaka''—rich in natural starch, B-complex vitamins, and soothing for digestive lining.', 4),
(25, 'Maanrh Jeera Digestive Tonic (Roasted Cumin Kanji Elixir)', 25, 'Baidya Biren Sen', 'Rural Bengal Ayurvedic Seva', 10, 'Easy', 'Digestive Soup/Rasam', 'Pure Veg', '["Roasted cumin powder (Bhuna Jeera)", "Black salt (Bit noon)", "Ghee", "Curry leaves", "Lime juice"]'::jsonb, '["Drain the thick, hot starch water (Maanrh / Kanji / Pej) after boiling open-pot rice.", "Pour into earthen cups while still warm.", "Stir in 1/2 tsp of pure cow ghee, roasted cumin powder, and mineral-rich black salt.", "Squeeze fresh lime juice and drink warm as an instant rehydration tonic before afternoon meals."]'::jsonb, 'Cooked rice starch water contains easily assimilable complex carbohydrates and electrolytes; it was traditional Indian medicine for fatigue and digestion.', 2),
(26, 'Paneer Whey Protein Rasam (Nutrient-Dense Tomato Broth)', 26, 'Chef Senthil Kumar', 'Zero-Waste South Indian Rasoi', 15, 'Easy', 'Main Curry', 'Pure Veg', '["Paneer whey water", "Chopped tomatoes", "Crushed garlic", "Crushed black pepper", "Cumin seeds", "Curry leaves", "Ghee", "Mustard seeds"]'::jsonb, '["Whenever you make paneer, chhena, or hung curd, never discard the yellowish liquid whey. It contains 100% of milk''s soluble proteins.", "In a saucepan, heat 1 tsp ghee. Splutter mustard seeds, cumin, and curry leaves.", "Add 4 crushed garlic cloves and 2 ripe chopped tomatoes. Cook until soft.", "Pour in 2.5 cups of fresh paneer whey water. Add 1/2 tsp turmeric, crushed black pepper, and salt.", "Bring to a gentle rolling simmer for 5 minutes. The whey lends a gentle natural tanginess, eliminating the need for heavy tamarind.", "Garnish with fresh coriander stems and serve as a soothing immunity soup or over hot rice."]'::jsonb, 'Nutritionist Insight: 1 liter of paneer whey contains roughly 8-10 grams of pure, highly digestible branched-chain amino acids (BCAAs).', 4),
(27, 'Tok Doi Gujarati Kadhi (Sweet & Tangy Leftover Curd Stew)', 27, 'Nani Hansa Ben', 'Ahmedabad Heritage Rasoi', 20, 'Easy', 'Dal/Sambar', 'Pure Veg', '["Besan (Gram flour)", "Ghee", "Cloves & Cinnamon", "Mustard & Cumin seeds", "Jaggery (Gor)", "Ginger-green chilli paste", "Salt"]'::jsonb, '["Whisk sour leftover curd with 2 tablespoons besan and 2 cups of water until completely smooth with no lumps.", "Add ginger-chilli paste, jaggery, and salt. Bring to a gentle boil on low heat, stirring continuously so curd does not curdle.", "In a small pan, heat ghee and temper with mustard, cumin, cloves, cinnamon, and curry leaves.", "Pour sputtering tadka into simmering kadhi. Simmer for 5 minutes and serve with warm khichdi."]'::jsonb, 'Never discard sour dahi! The lactic acidity is precisely what gives authentic Gujarati Kadhi its quintessential balance with sweet jaggery.', 4),
(28, 'Ghee Khurchan Mawa Ladoo (Caramelized Pan Solid Quick Sweets)', 28, 'Maa Annapurna Devi', 'Braj Ghee Heritage', 15, 'Easy', 'Breakfast/Snack', 'Pure Veg', '["Jaggery powder or Bura sugar", "Cardamom powder (Elaichi)", "Crushed almonds/cashews"]'::jsonb, '["Collect the golden-brown caramelized milk sediment (Khurchan / Berukho / Mor Kali) left in the pan after boiling butter into ghee.", "While still warm, transfer to a bowl and mash gently with a fork.", "Add equal parts powdered jaggery or bura sugar, a pinch of green cardamom powder, and crushed nuts.", "Roll into marble-sized bite sweets (ladoos) or simply toss with piping hot steamed rice for a heavenly traditional treat."]'::jsonb, 'Ghee khurchan is essentially slow-toasted artisanal mawa packed with buttery aroma; grandmothers considered it the sweetest reward of ghee-making day.', 6),
(29, 'Adrak Chilka Kadha (Immunity Boosting Ginger Peel Tisane)', 29, 'Acharya Baldev', 'Himalayan Herbal Kitchen', 12, 'Easy', 'Digestive Soup/Rasam', 'Vegan', '["Tulsi leaves", "Crushed black peppercorns", "Cinnamon bark", "Honey or Jaggery", "Water"]'::jsonb, '["Rinse peeled ginger skins well to wash away any soil traces. Air dry slightly.", "Bring 3 cups of water to a boil in a tea kettle.", "Add ginger skins, 5 crushed peppercorns, 1 cinnamon stick, and fresh tulsi leaves.", "Simmer covered for 8-10 minutes until aromatic and amber in color. Strain into cups and sweeten with raw honey or jaggery."]'::jsonb, 'The ginger peel and the layer immediately beneath it hold the highest concentration of gingerols and zingiberene volatile oils.', 3),
(30, 'Nariyal Brown Skin Idli Podi (Roasted Coconut Husk Gunpowder)', 30, 'Chef Senthil Murugan', 'Madurai Spice Guild', 15, 'Easy', 'Chutney/Dip', 'Vegan', '["Chana dal", "Urad dal", "Dry red chillies", "Curry leaves", "Asafoetida (Hing)", "Sesame oil", "Salt"]'::jsonb, '["Collect the thin brown skin shavings peeled when peeling fresh coconut for white sweets or chutneys.", "Dry roast the brown shavings in a heavy pan until nutty and completely crisp (do not burn).", "In the same pan, roast 2 tbsp chana dal, 2 tbsp urad dal, 6 red chillies, and curry leaves in 1/2 tsp sesame oil.", "Cool all ingredients and pulse in a dry mixer grinder with salt and hing into a coarse aromatic gunpowder spice mix.", "Serve mixed with cold-pressed sesame oil alongside hot idlis and crispy dosas."]'::jsonb, 'The fibrous brown coconut testa contains high insoluble fiber and rich natural aromatic oils that create legendary podi powders.', 8),
(31, 'Slow-Simmered Mutton Bone Broth (Paya Yakhni Soup)', 31, 'Ustad Abdul Kareem', 'Dakhni Heritage Rasoi, Hyderabad', 50, 'Medium', 'Soup/Broth', 'Non-Veg', '["Mutton bone knuckles", "Crushed black peppercorns", "Fresh ginger & garlic", "Turmeric powder", "Coriander seeds", "Green cardamom", "Ghee", "Fresh mint"]'::jsonb, '["Rinse mutton bone frames and knuckles thoroughly in warm salted water.", "Crack knuckles slightly with a heavy cleaver or pestle to expose marrow cavities for nutrient extraction.", "In a heavy-bottomed pot or pressure cooker, heat 1 tsp ghee; add bruised green cardamoms, crushed black pepper, ginger, and garlic until aromatic.", "Add bone frames and sear for 3 minutes. Pour 6 cups of water, add 1/2 tsp turmeric and salt.", "Slow-simmer on low flame for 45-60 minutes (or 6 whistles in cooker) until gelatinous marrow and collagen infuse the golden broth.", "Strain into bowls, sprinkle roasted cumin powder and fresh mint leaves. Serve piping hot with lemon wedges."]'::jsonb, 'Adding a splash of lemon during simmering leaches out maximum calcium and bioavailable collagen from the knuckle bones.', 4),
(32, 'Spiced Fish Head Rice Medley (Bengali Muri Ghonto)', 32, 'Ruma Mukherjee', 'Ganga Delta Home Kitchens, Kolkata', 35, 'Advanced', 'Main Course', 'Non-Veg', '["Rahu or Katla fish heads", "Fragrant Gobindobhog or Basmati rice", "Mustard oil", "Bay leaf & cumin seeds", "Onions & ginger paste", "Turmeric & Kashmiri chilli", "Garam masala & ghee"]'::jsonb, '["Halve fish head into manageable quarters, wash clean, and marinate with turmeric and salt.", "Deeply sear fish head pieces in hot mustard oil until golden brown and aromatic, breaking slightly with the spatula.", "In the remaining oil, temper whole garam masala, bay leaf, and cumin seeds; saut\u00e9 sliced onions and ginger-garlic paste until brown.", "Add rinsed fragrant rice and gently saut\u00e9 for 2 minutes to coat the grains in aromatic fat.", "Return the fried fish head pieces to the pan, add warm water (1:2 ratio to rice), cover and simmer on low for 15 minutes.", "Finish with a spoonful of aromatic ghee and garam masala. Let it rest 5 minutes before serving with steamed rice."]'::jsonb, 'Deeply frying the fish head until crisp eliminates any fishy odor and extracts rich omega-3 oils that cook the fragrant rice grains from within.', 4),
(33, 'Spiced Prawn Shell Chutney Powder & Broth', 33, 'Chef Meenakshi Sundaram', 'Coromandel Coastal Kitchen, Chennai', 25, 'Easy', 'Side Dish / Condiment', 'Non-Veg', '["Fresh prawn heads and shells", "Byadagi dried red chillies", "Urad dal & chana dal", "Curry leaves", "Tamarind pulp", "Garlic cloves", "Hing (Asafoetida)", "Sesame oil"]'::jsonb, '["Thoroughly rinse prawn heads and shells; pat completely dry on cotton kitchen towels.", "Dry-roast prawn shells on a cast iron pan over medium flame for 8-10 minutes until intensely fragrant, crisp, and brittle.", "Separately roast urad dal, chana dal, dried red chillies, garlic, and fresh curry leaves in 1/2 tsp sesame oil until aromatic.", "Let all ingredients cool down to room temperature.", "Transfer roasted shells, lentils, spices, salt, and tamarind into a spice grinder and pulse to a coarse, vibrant red podi.", "Store in an airtight jar. Serve with hot steamed rice and ghee, or sprinkle over crisp dosas."]'::jsonb, 'The prawn shells contain rich chitin and umami-heavy glutamates. Ensure they are bone-dry before grinding so the powder stays fresh for months.', 6),
(34, 'Rendered Chicken Schmaltz & Golden Cracklings', 34, 'Chef Zorawar Sethi', 'Grand Trunk Road Culinary Collective, Amritsar', 20, 'Easy', 'Side Dish / Condiment', 'Non-Veg', '["Trimmed chicken skin and charbi fat", "Coarse sea salt", "Crushed black pepper", "Chopped garlic cloves", "Sliced shallots"]'::jsonb, '["Chop chicken skin trimmings and solid fat pockets into bite-sized 1-inch squares.", "Place skin pieces in a cold skillet with 2 tablespoons of water over low-medium heat.", "As water evaporates, the chicken fat begins to slowly render out into clean, liquid golden cooking fat.", "Stir occasionally for 12-15 minutes until the skin pieces turn ultra-crispy, golden cracklings (chicharrones).", "Remove crispy cracklings with a slotted spoon onto paper towels; toss with rock salt and freshly crushed black pepper.", "Strain the rendered liquid chicken schmaltz into a glass jar\u2014use it as cooking oil for roasting potatoes or kneading dough."]'::jsonb, 'Starting with a small splash of water prevents the raw skin from burning while easing the low-temperature fat rendering process.', 4),
(35, 'Crispy Spiced Fish Roe Fritters (Machher Deem-er Bora)', 35, 'Chef Tanusree Ganguly', 'Bengal Byproduct Heritage Circle, Siliguri', 18, 'Easy', 'Snack / Fritter', 'Non-Veg', '["Fresh fish roe / egg sacs", "Finely chopped red onions", "Chopped green chillies", "Besan (Gram flour)", "Turmeric & kalonji (nigella) seeds", "Mustard oil for frying", "Rock salt"]'::jsonb, '["Wash fish roe gently under running water, removing any tough outer membrane veins.", "In a mixing bowl, gently mash fish roe using a fork; add finely chopped onions, green chillies, kalonji, turmeric, and salt.", "Add 1-2 tablespoons of besan (gram flour) strictly as a light binder\u2014do not add water as roe contains natural moisture.", "Heat mustard oil in a pan until it reaches smoking point, then reduce to medium.", "Drop tablespoon-sized balls of the mixture into hot oil and shallow fry for 2-3 minutes per side until golden and crunchy.", "Drain on paper towels and serve hot alongside steamed rice, yellow masoor dal, and green chillies."]'::jsonb, 'Do not over-mix or add extra water to the roe batter; the eggs naturally puff into tender, airy fritters with a delicate crisp shell.', 4);
SELECT setval('recipes_id_seq', (SELECT MAX(id) FROM recipes));

-- 5. INSERT 4 SAMPLE NGO DISPATCHES (100% CHENNAI SURPLUS FEED)
INSERT INTO ngo_dispatches (id, recipe_id, dish_name, scrap_source, prepared_by_chef, portions_available, pickup_location, contact_number, status, claimed_by_ngo, claim_otp, dietary_tag, ready_time, notes) VALUES
(1, 1, 'Peerkangai Thol Thogayal & Steamed Ponni Rice', '🥔 Ridge Gourd Peels', 'Chef R. Sundararajan (Annapoorna Community Kitchen)', 35, '28, North Mada Street, Mylapore, Chennai – 600004', '+91 94440 18234', 'ACTIVE', NULL, NULL, 'PURE VEG', 'Hot & Ready Now', 'Freshly ground traditional thogayal made from 4kg organic ridge gourd peel trimmings with urad dal and dry chillies. Packed with hot Ponni rice in thermal meal trays.'),
(2, 22, 'Kothu Chapati Tiffin & Vegetable Trimming Kurma', '🍚 Stale Rotis & Vegetable Trimmings', 'Nallur Seva Volunteers', 40, '15, Arcot Road, Porur (Near Ramapuram), Chennai – 600116', '+91 98402 77150', 'ACTIVE', NULL, NULL, 'PURE VEG', 'Hot & Ready Now', 'Upcycled shredded roti kothu tempered with mustard, curry leaves, and a nutrient-dense mixed vegetable stalk kurma.'),
(3, 29, 'Mor Kuzhambu & Vazhakkai Thol Thoran', '🥛 Sour Curd & Raw Banana Peels', 'Chef K. Meenakshi (Thirumalai Community Mess)', 50, '42, 2nd Avenue, Anna Nagar West, Chennai – 600040', '+91 98841 99230', 'CLAIMED', 'No Food Waste - Chennai Chapter (Anna Nagar Volunteer Wing)', '#CN-4821', 'PURE VEG', 'Hot & Ready Now', 'Traditional Mor Kuzhambu made from surplus sour churned dahi, served alongside dry tempered banana peel thoran.'),
(4, 31, 'Nalli Bone Broth & Steamed Samai Millets', '🍗 Bone Frames & Knuckles (Non-Veg Discards)', 'Chef Abdul Kareem (Heritage Rasoi)', 30, '12, Venkatanarayana Road, T. Nagar, Chennai – 600017', '+91 90877 90877', 'ACTIVE', NULL, NULL, 'NON-VEG (HALAL)', 'Hot & Ready Now', 'Nutrient-rich bone broth slow-simmered for 6 hours from mutton marrow knuckles with black pepper, coriander stems, and shallots. Served with hot little millets.');
SELECT setval('ngo_dispatches_id_seq', (SELECT MAX(id) FROM ngo_dispatches));
